import os
import io
import json
import webbrowser
from http.server import HTTPServer, BaseHTTPRequestHandler
from urllib.parse import urlparse, parse_qs
from datetime import datetime
from dotenv import load_dotenv
from box_sdk_gen import BoxClient, BoxOAuth, OAuthConfig, GetAuthorizeUrlOptions
import anthropic

load_dotenv()

CLIENT_ID = os.getenv("BOX_CLIENT_ID")
CLIENT_SECRET = os.getenv("BOX_CLIENT_SECRET")
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")
CONTRACTS_FOLDER_ID = "374250469285"

# ── Auth ──────────────────────────────────────────────────────────────────────

auth_code_holder = {}

class CallbackHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        parsed = urlparse(self.path)
        params = parse_qs(parsed.query)
        if "code" in params:
            auth_code_holder["code"] = params["code"][0]
        self.send_response(200)
        self.end_headers()
        self.wfile.write(b"Auth complete! You can close this tab.")
    def log_message(self, format, *args):
        pass

def get_box_client():
    oauth_config = OAuthConfig(client_id=CLIENT_ID, client_secret=CLIENT_SECRET)
    oauth = BoxOAuth(config=oauth_config)
    options = GetAuthorizeUrlOptions(redirect_uri="http://localhost:8080/callback", response_type="code")
    auth_url = oauth.get_authorize_url(options=options)
    print("🔐 Opening browser for Box login...")
    webbrowser.open(auth_url)
    server = HTTPServer(("localhost", 8080), CallbackHandler)
    server.handle_request()
    oauth.get_tokens_authorization_code_grant(authorization_code=auth_code_holder["code"])
    return BoxClient(auth=oauth)

# ── Step 1: Fetch PDF bytes from Box ─────────────────────────────────────────

def download_file_bytes(client, file_id):
    stream = client.downloads.download_file(file_id)
    return stream.read()

# ── Step 2: Analyze each contract with Claude ────────────────────────────────

SYSTEM_PROMPT = """You are a senior legal analyst specializing in enterprise contract risk review.
You will be given a contract PDF. Analyze it and return a JSON object with exactly this structure:

{
  "contract_name": "string",
  "contract_id": "string",
  "parties": ["Party A", "Party B"],
  "contract_type": "string",
  "effective_date": "string",
  "expiration_date": "string or null",
  "risk_level": "LOW | MEDIUM | HIGH",
  "risk_score": <integer 1-10>,
  "flags": [
    {
      "severity": "HIGH | MEDIUM | LOW",
      "clause": "string",
      "issue": "string",
      "recommendation": "string"
    }
  ],
  "summary": "2-3 sentence plain English summary of the contract and its key risks"
}

Return ONLY valid JSON. No preamble, no markdown, no explanation."""

def analyze_contract(file_name, pdf_bytes):
    import base64
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
    
    print(f"  🤖 Sending to Claude...")
    response = client.messages.create(
        model="claude-opus-4-6",
        max_tokens=1500,
        system=SYSTEM_PROMPT,
        messages=[
            {
                "role": "user",
                "content": [
                    {
                        "type": "document",
                        "source": {
                            "type": "base64",
                            "media_type": "application/pdf",
                            "data": base64.standard_b64encode(pdf_bytes).decode("utf-8"),
                        },
                    },
                    {
                        "type": "text",
                        "text": f"Please analyze this contract: {file_name}"
                    }
                ],
            }
        ],
    )
    
    raw = response.content[0].text.strip()
    # Strip markdown fences if present
    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]
    return json.loads(raw.strip())

# ── Step 3: Build the markdown report ────────────────────────────────────────

RISK_EMOJI = {"LOW": "🟢", "MEDIUM": "🟡", "HIGH": "🔴"}
SEV_EMOJI = {"LOW": "⚠️", "MEDIUM": "🚨", "HIGH": "🔴"}

def build_report(results):
    now = datetime.now().strftime("%B %d, %Y at %H:%M")
    high_count = sum(1 for r in results if r["risk_level"] == "HIGH")
    medium_count = sum(1 for r in results if r["risk_level"] == "MEDIUM")
    low_count = sum(1 for r in results if r["risk_level"] == "LOW")
    avg_score = sum(r["risk_score"] for r in results) / len(results)

    lines = []
    lines.append("# Contract Risk Review Report")
    lines.append(f"**Generated by:** Box + Claude AI Agent  ")
    lines.append(f"**Date:** {now}  ")
    lines.append(f"**Company:** The Demoman Company  ")
    lines.append(f"**Contracts Reviewed:** {len(results)}  ")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Portfolio Summary")
    lines.append("")
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Total Contracts | {len(results)} |")
    lines.append(f"| 🔴 High Risk | {high_count} |")
    lines.append(f"| 🟡 Medium Risk | {medium_count} |")
    lines.append(f"| 🟢 Low Risk | {low_count} |")
    lines.append(f"| Average Risk Score | {avg_score:.1f} / 10 |")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Contract Details")
    lines.append("")

    # Sort by risk score descending
    for r in sorted(results, key=lambda x: x["risk_score"], reverse=True):
        emoji = RISK_EMOJI.get(r["risk_level"], "⚪")
        lines.append(f"### {emoji} {r['contract_name']}")
        lines.append("")
        lines.append(f"| Field | Value |")
        lines.append(f"|-------|-------|")
        lines.append(f"| Contract ID | {r['contract_id']} |")
        lines.append(f"| Type | {r['contract_type']} |")
        lines.append(f"| Parties | {' & '.join(r['parties'])} |")
        lines.append(f"| Effective Date | {r['effective_date']} |")
        lines.append(f"| Expiration | {r.get('expiration_date') or 'None (Evergreen)'} |")
        lines.append(f"| Risk Level | {emoji} {r['risk_level']} |")
        lines.append(f"| Risk Score | {r['risk_score']} / 10 |")
        lines.append("")
        lines.append(f"**Summary:** {r['summary']}")
        lines.append("")

        if r.get("flags"):
            lines.append("**Flagged Clauses:**")
            lines.append("")
            for flag in r["flags"]:
                sev = SEV_EMOJI.get(flag["severity"], "⚠️")
                lines.append(f"- {sev} **{flag['clause']}**")
                lines.append(f"  - Issue: {flag['issue']}")
                lines.append(f"  - Recommendation: {flag['recommendation']}")
                lines.append("")
        lines.append("---")
        lines.append("")

    lines.append("*This report was generated automatically by an AI agent. "
                 "It is not legal advice. Please consult qualified legal counsel "
                 "before making decisions based on this analysis.*")
    return "\n".join(lines)

# ── Step 4: Upload report back to Box ────────────────────────────────────────

def upload_report(client, folder_id, content):
    now = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"contract_risk_report_{now}.md"
    file_bytes = content.encode("utf-8")
    buffer = io.BytesIO(file_bytes)
    buffer.name = filename

    from box_sdk_gen import UploadFileAttributes, UploadFileAttributesParentField
    attributes = UploadFileAttributes(
        name=filename,
        parent=UploadFileAttributesParentField(id=folder_id)
    )
    response = client.uploads.upload_file(attributes=attributes, file=buffer)
    uploaded = response.entries[0]
    print(f"\n✅ Report uploaded to Box: {uploaded.name} (id: {uploaded.id})")
    return uploaded

# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    print("=" * 60)
    print("  BOX CONTRACT RISK AGENT")
    print("  Powered by Claude AI")
    print("=" * 60)

    # Auth
    box_client = get_box_client()
    print("✅ Authenticated with Box\n")

    # Get files
    items = client_files = box_client.folders.get_folder_items(CONTRACTS_FOLDER_ID)
    pdfs = [f for f in items.entries if f.name.endswith(".pdf")]
    print(f"📁 Found {len(pdfs)} contracts to review\n")

    # Analyze each
    results = []
    for i, pdf in enumerate(pdfs, 1):
        print(f"[{i}/{len(pdfs)}] Analyzing: {pdf.name}")
        pdf_bytes = download_file_bytes(box_client, pdf.id)
        result = analyze_contract(pdf.name, pdf_bytes)
        results.append(result)
        risk_emoji = RISK_EMOJI.get(result["risk_level"], "⚪")
        print(f"  {risk_emoji} Risk: {result['risk_level']} (score: {result['risk_score']}/10)\n")

    # Build report
    print("📝 Building risk report...")
    report = build_report(results)

    # Upload to Box
    print("📤 Uploading report to Box...")
    upload_report(box_client, CONTRACTS_FOLDER_ID, report)

    print("\n🎉 Done! Check your Box contracts folder for the report.")
    print("=" * 60)

if __name__ == "__main__":
    main()